import type { ProgramId } from '../data/programs'

export interface LocalizedProgramDetail {
  promise: string
  subtitle: string
  problem: string
  result: string
  audience: string[]
  notFor: string[]
  included: string[]
  workflow: Array<{ title: string; description: string }>
  benefits: string[]
  exclusions: string[]
  caseStudy: { context: string; action: string; outcome: string | null } | null
  faq: Array<{ question: string; answer: string }>
  specificConditions: string[]
}

export const programDetailsI18n = {
  es: {
    care: {
      promise: 'Tu barco, cuidado todo el año por una sola persona a la que llamar.',
      subtitle: 'Proveedores y presupuestos: tú solo decides.',
      problem: 'Mantener el barco al día exige ordenar revisiones, presupuestos, especialistas y fechas durante todo el año.',
      result: 'Una planificación anual, decisiones informadas y seguimiento documentado desde una única interlocución.',
      audience: ['Propietarios que quieren conservar el control de las decisiones sin encargarse de cada coordinación.'],
      notFor: ['Quien necesita una peritación o una inspección obligatoria en lugar de un servicio continuado de coordinación.'],
      included: ['Una persona responsable como interlocutora única.', 'Visita mensual de una hora con fotografías.', 'Planificación anual del mantenimiento.', 'Comparación de presupuestos.', 'Coordinación y seguimiento de especialistas.', 'Logística relacionada con las intervenciones aprobadas.', 'Asistencia diaria por teléfono o vídeo.', 'Visita y diagnóstico en un máximo de 48 horas laborables.', 'Informe anual del estado y de las actuaciones.'],
      workflow: [{ title: 'Planificación', description: 'Revisamos las necesidades y ordenamos el año de mantenimiento.' }, { title: 'Seguimiento', description: 'Realizamos la visita mensual y coordinamos las actuaciones aprobadas.' }, { title: 'Cierre anual', description: 'Entregamos un informe con el trabajo realizado y las próximas prioridades.' }],
      benefits: ['Un único punto de contacto para saber qué necesita el barco.', 'Presupuestos comparados antes de decidir.', 'Seguimiento documentado con fotografías e informe anual.'],
      exclusions: ['Materiales, repuestos y trabajos de especialistas.', 'Peritaciones e inspecciones obligatorias.'],
      caseStudy: { context: 'Durante el invierno, un Brenta 42 y un Van Dutch 40 necesitaban un plan con varios especialistas.', action: 'Se compararon opciones de varadero para coordinar los trabajos.', outcome: 'Se eligió un espacio interior con mejor precio y una botadura flexible.' },
      faq: [{ question: '¿El diagnóstico de una avería consume horas de la bolsa?', answer: 'No. El diagnóstico de avería no descuenta horas de la bolsa mensual.' }, { question: '¿La cuota incluye materiales y trabajos externos?', answer: 'No. Se presupuestan y se aprueban antes de realizarse.' }],
      specificConditions: ['El diagnóstico de avería no descuenta horas de la bolsa.', 'La visita y el diagnóstico se realizan en un máximo de 48 horas laborables.'],
    },
    navigation: {
      promise: 'Tu asesor de electrónica, para que todo funcione cuando largues amarras.', subtitle: 'Auditamos, recomendamos e instalamos.', problem: 'Los sistemas eléctricos y electrónicos necesitan una revisión coordinada para detectar prioridades antes de navegar.', result: 'Un informe tipo semáforo, prioridades claras y comprobación de las actuaciones aprobadas.',
      audience: ['Propietarios que quieren conocer el estado de sus equipos y decidir con una recomendación clara.'], notFor: ['Quien busca comprar equipos sin una auditoría previa ni comprobar después su funcionamiento a bordo.'],
      included: ['Auditoría eléctrica y electrónica.', 'Informe tipo semáforo con prioridades.', 'Recomendaciones de mantenimiento, reparación o actualización.', 'Coordinación de especialistas.', 'Suministro e instalación cuando corresponda y exista aprobación previa.', 'Prueba de mar.', 'Soporte sobre los equipos instalados.', 'Comprobación previa a travesías largas.'],
      workflow: [{ title: 'Auditoría', description: 'Comprobamos la instalación eléctrica y los equipos electrónicos.' }, { title: 'Prioridades', description: 'Entregamos un informe tipo semáforo y una recomendación para cada hallazgo.' }, { title: 'Comprobación', description: 'Coordinamos lo aprobado y verificamos el resultado, incluida la prueba de mar cuando corresponda.' }],
      benefits: ['Una visión ordenada del estado de los sistemas.', 'Prioridades comprensibles antes de autorizar gastos.', 'Comprobación del funcionamiento tras las actuaciones aprobadas.'], exclusions: ['Equipos, cableado y materiales, que se presupuestan aparte.', 'Trabajos externos no aprobados previamente.'],
      caseStudy: { context: 'Un mismo cliente solicitó una revisión eléctrica para dos embarcaciones.', action: 'La revisión eléctrica de ambas embarcaciones se programó para diciembre.', outcome: null },
      faq: [{ question: '¿Los equipos y materiales están incluidos?', answer: 'No. Los equipos, el cableado y los materiales se presupuestan aparte para su aprobación.' }, { question: '¿Se comprueba el resultado de la instalación?', answer: 'Sí. El servicio incluye la comprobación y, cuando corresponde, una prueba de mar.' }],
      specificConditions: ['El suministro y la instalación se realizan únicamente cuando corresponda y tras la aprobación del presupuesto.', 'El soporte incluido se refiere a los equipos instalados dentro del servicio.'],
    },
    ready: {
      promise: 'Tu barco limpio, toda la temporada.', subtitle: 'Limpieza y detailing profesional, en otoño y en primavera.', problem: 'La limpieza y la conservación requieren coordinación y supervisión en los momentos clave de la temporada.', result: 'Dos limpiezas planificadas al año, supervisión del resultado y registro fotográfico.',
      audience: ['Propietarios que quieren dos limpiezas completas al año con seguimiento antes y después del trabajo.'], notFor: ['Quien necesita reparaciones, tapicería o tratamientos especiales incluidos automáticamente en la cuota.'],
      included: ['Dos limpiezas completas al año.', 'Coordinación y supervisión de los trabajos.', 'Limpieza interior y exterior.', 'Revisión de textiles y fundas.', 'Fotografías antes y después.', 'Aviso temprano de incidencias detectadas durante la revisión.'],
      workflow: [{ title: 'Revisión', description: 'Comprobamos el estado y organizamos la limpieza de temporada.' }, { title: 'Limpieza', description: 'Coordinamos y supervisamos el trabajo interior y exterior.' }, { title: 'Verificación', description: 'Revisamos el resultado y entregamos fotografías antes y después.' }],
      benefits: ['Dos momentos de limpieza planificados durante el año.', 'Supervisión del resultado y registro fotográfico.', 'Detección temprana de incidencias visibles.'], exclusions: ['Pulido de casco y cubierta: servicio adicional bajo presupuesto.', 'Teca, tapicería, reparaciones y materiales especiales.'], caseStudy: null,
      faq: [{ question: '¿Cuántas limpiezas incluye el programa?', answer: 'Incluye dos limpiezas completas al año, una en otoño y otra en primavera.' }, { question: '¿El pulido está incluido?', answer: 'No. El pulido de casco y cubierta es un servicio adicional bajo presupuesto.' }],
      specificConditions: ['La hora mensual cubre coordinación y verificación; no incluye las horas del equipo de limpieza externo.', 'Pulido, teca, tapicería, reparaciones y materiales especiales requieren presupuesto.'],
    },
    complete: {
      promise: 'Dinos cuándo quieres salir; del resto nos ocupamos nosotros.', subtitle: 'Los tres planes en uno, con asistencia en 48 h e informe anual. Ahorras hasta un 16 %.', problem: 'Coordinar mantenimiento, electrónica y limpieza por separado dificulta tener una visión común del estado del barco.', result: 'Los tres planes coordinados por una única persona, con una visión anual común de las actuaciones.',
      audience: ['Propietarios que quieren reunir los tres planes bajo una sola persona responsable.'], notFor: ['Quien solo necesita una actuación aislada sin seguimiento durante el año.'], included: ['Todas las prestaciones de los tres planes.', 'Una persona responsable como interlocutora única.', 'Aviso de incidencias.', 'Asistencia y diagnóstico en un máximo de 48 horas laborables.', 'Informe anual.', 'Comprobación previa a la salida con 48 horas de aviso.'],
      workflow: [{ title: 'Plan común', description: 'Reunimos mantenimiento, electrónica y limpieza en una planificación anual.' }, { title: 'Coordinación', description: 'Una sola persona sigue las actuaciones y comunica las incidencias.' }, { title: 'Antes de salir', description: 'Con 48 horas de aviso, realizamos la comprobación previa a la salida.' }],
      benefits: ['Los tres planes coordinados por una única persona.', 'Una visión anual común del estado y las actuaciones.', 'Un ahorro mensual de hasta un 16 % frente a contratar los planes por separado.'], exclusions: ['Materiales, repuestos y trabajos externos sin presupuesto y aprobación previa.', 'Actuaciones que no estén incluidas en alguno de los tres planes.'], caseStudy: null,
      faq: [{ question: '¿Qué reúne Listo para Zarpar?', answer: 'Reúne Mantenimiento Delegado, Electrónica Asesorada y Limpieza y Detailing.' }, { question: '¿Con cuánto tiempo debo avisar antes de salir?', answer: 'La comprobación previa a la salida requiere un aviso de 48 horas.' }], specificConditions: ['La comprobación previa a la salida requiere 48 horas de aviso.', 'Las condiciones específicas de cada uno de los tres planes siguen siendo aplicables.'],
    },
  },
  en: {
    care: {
      promise: 'Your boat, cared for all year round by one person you can call.', subtitle: 'Suppliers and quotes: you only make the decisions.', problem: 'Keeping a boat up to date means organising inspections, quotes, specialists and dates throughout the year.', result: 'An annual plan, informed decisions and documented follow-up through a single point of contact.', audience: ['Boat owners who want to retain control of decisions without managing every coordination task.'], notFor: ['Anyone who needs a survey or mandatory inspection instead of an ongoing coordination service.'],
      included: ['One responsible person as your single point of contact.', 'A one-hour monthly visit with photographs.', 'Annual maintenance planning.', 'Quote comparison.', 'Coordination and follow-up of specialists.', 'Logistics related to approved work.', 'Daily assistance by phone or video.', 'Visit and diagnosis within a maximum of 48 business hours.', 'Annual condition and work report.'],
      workflow: [{ title: 'Planning', description: 'We review the requirements and organise the maintenance year.' }, { title: 'Follow-up', description: 'We carry out the monthly visit and coordinate approved work.' }, { title: 'Annual close', description: 'We provide a report covering completed work and the next priorities.' }], benefits: ['One point of contact to understand what the boat needs.', 'Quotes compared before you decide.', 'Documented follow-up with photographs and an annual report.'], exclusions: ['Materials, spare parts and specialist work.', 'Surveys and mandatory inspections.'], caseStudy: { context: 'During the winter, a Brenta 42 and a Van Dutch 40 needed a plan involving several specialists.', action: 'Boatyard options were compared in order to coordinate the work.', outcome: 'An indoor space with a better price and a flexible launch date was selected.' }, faq: [{ question: 'Does diagnosing a fault use hours from the allowance?', answer: 'No. Fault diagnosis does not deduct hours from the monthly allowance.' }, { question: 'Does the fee include materials and external work?', answer: 'No. They are quoted and approved before the work is carried out.' }], specificConditions: ['Fault diagnosis does not deduct hours from the allowance.', 'The visit and diagnosis are carried out within a maximum of 48 business hours.'],
    },
    navigation: {
      promise: 'Your marine electronics adviser, so everything works when you cast off.', subtitle: 'We audit, recommend and install.', problem: 'Electrical and electronic systems need a coordinated review to identify priorities before you sail.', result: 'A traffic-light report, clear priorities and verification of approved work.', audience: ['Boat owners who want to understand the condition of their equipment and decide with a clear recommendation.'], notFor: ['Anyone looking to buy equipment without a prior audit or a subsequent check of its operation on board.'], included: ['Electrical and electronics audit.', 'Traffic-light report with priorities.', 'Maintenance, repair or upgrade recommendations.', 'Coordination of specialists.', 'Supply and installation where appropriate and subject to prior approval.', 'Sea trial.', 'Support for installed equipment.', 'Pre-check before long passages.'], workflow: [{ title: 'Audit', description: 'We check the electrical installation and electronic equipment.' }, { title: 'Priorities', description: 'We provide a traffic-light report and a recommendation for each finding.' }, { title: 'Verification', description: 'We coordinate the approved work and verify the result, including a sea trial where appropriate.' }], benefits: ['An organised view of the systems’ condition.', 'Clear priorities before authorising expenditure.', 'Operational checks after the approved work.'], exclusions: ['Equipment, wiring and materials, which are quoted separately.', 'External work not approved in advance.'], caseStudy: { context: 'The same customer requested an electrical inspection for two boats.', action: 'The electrical inspection of both boats was scheduled for December.', outcome: null }, faq: [{ question: 'Are equipment and materials included?', answer: 'No. Equipment, wiring and materials are quoted separately for approval.' }, { question: 'Is the result of the installation checked?', answer: 'Yes. The service includes verification and, where appropriate, a sea trial.' }], specificConditions: ['Supply and installation are carried out only where appropriate and after the quote has been approved.', 'Included support applies to equipment installed as part of the service.'],
    },
    ready: {
      promise: 'Your boat clean throughout the season.', subtitle: 'Professional cleaning and detailing in autumn and spring.', problem: 'Cleaning and upkeep require coordination and supervision at key points in the season.', result: 'Two scheduled cleanings per year, result supervision and a photographic record.', audience: ['Boat owners who want two full cleanings per year with follow-up before and after the work.'], notFor: ['Anyone who needs repairs, upholstery work or special treatments automatically included in the fee.'], included: ['Two full cleanings per year.', 'Coordination and supervision of the work.', 'Interior and exterior cleaning.', 'Inspection of textiles and covers.', 'Before-and-after photographs.', 'Early notification of issues identified during the inspection.'], workflow: [{ title: 'Inspection', description: 'We check the condition and organise the seasonal cleaning.' }, { title: 'Cleaning', description: 'We coordinate and supervise the interior and exterior work.' }, { title: 'Verification', description: 'We check the result and provide before-and-after photographs.' }], benefits: ['Two planned cleaning points during the year.', 'Result supervision and a photographic record.', 'Early detection of visible issues.'], exclusions: ['Hull and deck polishing: an additional service subject to quotation.', 'Teak, upholstery, repairs and special materials.'], caseStudy: null, faq: [{ question: 'How many cleanings does the plan include?', answer: 'It includes two full cleanings per year, one in autumn and one in spring.' }, { question: 'Is polishing included?', answer: 'No. Hull and deck polishing is an additional service subject to quotation.' }], specificConditions: ['The monthly hour covers coordination and verification; it does not include the external cleaning team’s working hours.', 'Polishing, teak, upholstery, repairs and special materials require a quote.'],
    },
    complete: {
      promise: 'Tell us when you want to go out; we will take care of the rest.', subtitle: 'All three plans in one, with assistance within 48 hours and an annual report. Save up to 16%.', problem: 'Coordinating maintenance, electronics and cleaning separately makes it harder to maintain a shared view of the boat’s condition.', result: 'All three plans coordinated by one person, with one shared annual view of the work.', audience: ['Boat owners who want to bring all three plans under one responsible person.'], notFor: ['Anyone who only needs a one-off job without follow-up throughout the year.'], included: ['All services included in the three plans.', 'One responsible person as your single point of contact.', 'Issue notifications.', 'Assistance and diagnosis within a maximum of 48 business hours.', 'Annual report.', 'Pre-departure check with 48 hours’ notice.'], workflow: [{ title: 'Shared plan', description: 'We bring maintenance, electronics and cleaning together in one annual plan.' }, { title: 'Coordination', description: 'One person follows the work and communicates any issues.' }, { title: 'Before departure', description: 'With 48 hours’ notice, we carry out the pre-departure check.' }], benefits: ['All three plans coordinated by one person.', 'One shared annual view of the condition and the work.', 'Monthly savings of up to 16% compared with purchasing the plans separately.'], exclusions: ['Materials, spare parts and external work without a quote and prior approval.', 'Work not included in any of the three plans.'], caseStudy: null, faq: [{ question: 'What does Ready to Cast Off include?', answer: 'It brings together Delegated Maintenance, Expert-Guided Electronics and Cleaning & Detailing.' }, { question: 'How much notice do I need to give before departure?', answer: 'The pre-departure check requires 48 hours’ notice.' }], specificConditions: ['The pre-departure check requires 48 hours’ notice.', 'The specific conditions of each of the three plans continue to apply.'],
    },
  },
} satisfies Record<'es' | 'en', Record<ProgramId, LocalizedProgramDetail>>
